spring:
  application:
    name: simple

  config:
    import:
      - app/example/example.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

    # connection pool (usage: hikari pool)
    hikari:
      connection-timeout: 30_000
      idle-timeout: 60_000
      max-lifetime: 1_800_000
      maximum-pool-size: 300
      minimum-idle: 5
      leak-detection-threshold: 2000

  flyway:
    baseline-on-migrate: true # flyway schema history ???? ??? ????.